const domain_prefix = "http://localhost:5000/";
// const domain_prefix = "http://192.168.1.107:5000/";
// const domain_prefix = "https://bcs-backend-qulo-nwegr5exe-abdulrehman67s-projects.vercel.app/";
export const LOG_IN = domain_prefix + "auth/login";
export const CREATE_ACCOUNT = domain_prefix + "auth/create-user";
export const GET_ALL_BOOKS = domain_prefix + "book/get-book";
export const UPDATE_BOOK = domain_prefix + "book/update-book";
export const DELETE_BOOK = domain_prefix + "book/delete-book";
export const ADD_BOOK = domain_prefix + "book/add-book";
